coursemanager/urls.py
from django.urls import path
from .views import *

app_name = 'coursemanager'
urlpatterns = [
    path('courses/', CourseList.as_view(), name='course-list'),
]

seedofknowledge/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('django.contrib.auth.urls')),
    path('', frontpage, name='frontpage'),
    path('dashboard/', dashboard, name='dashboard'),
    path('register/', register, name='register'),
    path('setup/', include('setup.urls')),
    path('courses/', include('course.urls')),
    path('registrar/', include('registrar.urls')),
    path('students/', include('students.urls')),
    path('teacher/', include('teacher.urls')),
    path('coursemanager/', include('coursemanager.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

setup/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('users/', UserList.as_view(), name='user-list'),
    path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
    path('users/<int:pk>/make_course_manager/', make_course_manager, name='make-course-manager'),
    path('users/<int:pk>/revoke_course_manager/', revoke_course_manager, name='revoke-course-manager'),
    path('users/<int:pk>/make_registrar/', make_registrar, name='make-registrar'),
    path('users/<int:pk>/revoke_registrar/', revoke_registrar, name='revoke-registrar'),

    path('schools/', SchoolList.as_view(), name='school-list'),
    path('schools/create/', SchoolCreate.as_view(), name='school-create'),

    path('schools/<int:pk>/', SchoolDetail.as_view(), name='school-detail'),
    path('schools/<int:pk>/add_classroom/', ClassroomCreate.as_view(), name='classroom-create'),
    path('teachers/', TeacherList.as_view(), name='teacher-list'),
    path('teachers/create/', TeacherCreate.as_view(), name='teacher-create'),
]

core/models.py
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django.conf import settings
from django.dispatch import receiver

# Create your models here.

class ScorecardActivity(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

class Scorecard(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
            on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    activity = models.ForeignKey('ScoreCardActivity', on_delete=models.CASCADE)
    description = models.TextField()
    points = models.IntegerField()

    def __str__(self):
        # XXX: I'll figure out later what to do with this.
        return self.user.username + " " + self.points

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE)
    course_manager = models.BooleanField(default=False)
    registrar = models.BooleanField(default=False)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def total_score(self):
        a = Scorecard.objects.filter(user=self.user).aggregate(Sum('points'))
        return a['points__sum'] or 0

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=255, 
            help_text='Required. Enter a valid email.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm

# Create your views here.

def frontpage(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        return render(request, 'core/frontpage.html', {})

@login_required
def dashboard(request):
    return render(request, 'core/dashboard.html', {})
        
def register(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    elif request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'core/register.html', {'form': form})

core/templates/base.html
<!doctype html>
{% load bootstrap4 %}
{% load static %}

<html class="h-100">
  <head>
    <title></title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block js %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/seedofknowledge.css' %}">
  </head>

  <body class="h-100">
    <nav class="navbar navbar-expand-sm navbar-dark py-1" style="background-color: #006000;">
      <a class="navbar-brand" href="#">Seed of Knowledge</a>
      <div class="navbar-collapse navbar" id="collapsingNavbar">
        {% block navbar %}
        {% endblock %}
      </div>
    </nav>

    <header>
      {% block header %}
      {% endblock %}
    </header>

    {% block main %}
    {% endblock %}

    <footer class="footer">
      {% block footer %}
      <div class="text-muted text-center py-3">
        <small>Copyright &copy; 2018, Seed Of Knowledge</small>
      </div>
      {% endblock %}
    </footer>
  </body>
</html>

{# vim: set ft=htmldjango : #}

core/templates/base_authenticated.html
{% extends "base.html" %}
{% load static %}
{% load notifications_tags %}

{% block js %}
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
{% endblock %}

{% block navbar %}
<ul class="navbar-nav mx-auto">
  <li class="nav-item">
    <a class="nav-link py-0" href="{% url 'dashboard' %}">Home</a>
  </li>

  {% if user.is_superuser %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle py-0" href="#" id="setupDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Setup
    </a>
    <div class="dropdown-menu" aria-labelledby="setupDropdown">
      <a class="dropdown-item" href="{% url 'user-list' %}">Users</a>
      <a class="dropdown-item" href="{% url 'school-list' %}">Schools</a>
      <a class="dropdown-item" href="{% url 'teacher-list' %}">Teachers</a>
    </div>
  </li>
  {% endif %}

  {% if user.profile.course_manager %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle py-0" href="#" id="courseManagementDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Course Management
    </a>
    <div class="dropdown-menu" aria-labelledby="coureManagementDropdown">
      <a class="dropdown-item" href="{% url 'course-category-list' %}">Categories</a>
      <a class="dropdown-item" href="{% url 'coursemanager:course-list' %}">Courses</a>
    </div>
  </li>
  {% endif %}

  {% if user.profile.registrar %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle py-0" href="#" id="registrarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Registrar
    </a>
    <div class="dropdown-menu" aria-labelledby="registrarDropdown">
      <a class="dropdown-item" href="{% url 'study-group-list' %}">Study Groups</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'unassigned-students-by-course' %}">Unassigned Students by Course</a>
    </div>
  </li>
  {% endif %}

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle py-0" href="#" id="studentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Student
    </a>
    <div class="dropdown-menu" aria-labelledby="studentDropdown">
      <a class="dropdown-item" href="{% url 'course-catalog' %}">Course Catalog</a>
    </div>
  </li>
</ul>

<ul class="navbar-nav ml-auto">
  <li class="navbar-item">
    <a class="nav-link py-0" href="{% url 'notifications:unread' %}">
      {% live_notify_badge badge_class="badge" %}
    </a>
  </li>

  <li class="navbar-item">
    <a class="nav-link py-0" href="{% url 'logout' %}">Logout</a>
  </li>
</ul>
{% endblock %}